# Generated by Django 5.0.6 on 2024-05-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.CharField(max_length=10)),
                ('num2', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=15)),
            ],
        ),
    ]
